### ISSUE TITLE
example/scripts

### ISSUE THREAD

**Issue by chuckie82** [chuckie82/pysingfel#108]
Due to active development (API changes etc), example scripts quickly become outdated and don't work anymore.

it would be great if we can run example scripts in pytest

**Comment by chuckie82** [comment]
@apeck12 @irischang020
Here's a way to convert notebooks to python script for continuous integration:
https://nbconvert.readthedocs.io/en/latest/usage.html#convert-script

**Comment by apeck12** [comment]
Thanks for that conversion tool. A few questions:

1. It seems like the purpose of most examples is to provide visual demonstrations, so I'm not sure how best to run them in pytest. Do we want the tests to: (a) check that each example outputs the expected result, which is pre-computed and stored as an array in the examples folder, (b) simply verify that the scripts run without throwing errors, and/or (c) confirm that the results using psana1 and psana2 match?

2. What should be done with undocumented example scripts? I'm not sure what the objective is for some of these.

3. Do we want to keep the current organization of all examples in one folder, and have a test.py script run through all of them? Some of the examples seem more relevant to specific classes, but these examples are more complex than the class-specific unit tests.

**Comment by irischang020** [comment]
I can work on #2 to clean up or add descriptions for the undocumented example scripts.

**Comment by chuckie82** [comment]
1. I think it would be suffice to check that it runs without throwing errors.
2. Iris can work on undocumented example scripts. Each script should describe its purpose at the top of the script. I vote to remove any scripts that are just modified copies of other scripts.
3. I think one example folder is ok. I view running example scripts as an integration test and functional test.

**Comment by irischang020** [comment]
Working on converting notebooks to python scripts, and planning to have the following in the example folder:
ExampleSPI.py
ExampleFXS.py
ExampleHolography.py
ExampleSASE.py
ExampleAutoranging.py
ExampleAggragate.py
ExampleHydration.py
(ExampleFilling.py)
ExampleComformation.py

Feel free to suggest any other examples that we want to demonstrate the usages.
