### ISSUE TITLE
pysingfel in PyPI

### ISSUE THREAD

**Issue by fredericpoitevin** [chuckie82/pysingfel#121]
The version of pysingfel on PyPI has not been updated in 3 years. Should we remove the PyPI project or try to update it?

**Comment by chuckie82** [comment]
Haoyuan created it on PyPI 3 years ago which he "maintains" from his github repo. 

If there's a real need to be on PyPI, we can push our changes to haoyuanli93/pysingfel
Otherwise, we could give pysingfel a new name and maintain it

**Comment by fredericpoitevin** [comment]
@ynashed is interested in installing pysingfel within a docker image and tried `pip install pysingfel`, which would probably be the best guess for most users who want to do the same thing... (easier than git cloning and then local pip install)

I like the second option, I guess we just need to know the new name :D

**Comment by ynashed** [comment]
Either would be fine for my use case. Keeping the name would be ideal to avoid confusion.

**Comment by chuckie82** [comment]
moved pysingfel to skopi: https://github.com/chuckie82/skopi
Available on pypi as skopi
