### ISSUE TITLE
Calibration constants for Epix10k Detectors

### ISSUE THREAD

**Issue by apeck12** [chuckie82/pysingfel#123]
For the Epix10k detector, the calibration files (e.g. pedestal, pixel_status, etc.) seem to have seven values per pixel:
```
detector.pedestals.shape: (7,16,352,384)
shot.shape: (16,352,384) # random data frame taken from exp=xcsx39618
```
Do these values correspond to different camera configurations? However, there appear to be only five configurations (two auto-ranging, three fixed), so I’m not sure which set of calibration constants is the appropriate one to use in different circumstances, e.g. for adding in pedestal-subtracted dark noise.

**Comment by chuckie82** [comment]
this might be a question for Mikhail

**Comment by apeck12** [comment]
Mikhail said that the different indices correspond to different gain ranges, as specified [here](https://confluence.slac.stanford.edu/display/PSDM/EPIX10KA#EPIX10KA-Gaincorrectionfiles). He also suggested using the psana `det.calib(...)` method to apply corrections rather than working with the pedestal and other calibration files directly, so I'll pursue that strategy when adding dark noise. Closing this issue.
