### ISSUE TITLE
Remove hdf5 file

### ISSUE THREAD

**Issue by AntoineDujardin** [chuckie82/pysingfel#17]
There is a 41MB file at examples/scripts/imStack.hdf5, which should be removed & purged.

**Comment by AntoineDujardin** [comment]
BFG seems the way to go:
https://help.github.com/en/articles/removing-sensitive-data-from-a-repository

Note: erasing a file from the history is going to change all the commit since the moment it was added. That might make pull request difficult. They recommend synchronizing everyone before doing so.

**Comment by AntoineDujardin** [comment]
Waiting for chuckie82/pysingfel/pull/18, then we should sync Marc's code.

**Comment by AntoineDujardin** [comment]
/pull/18 merged, waiting for @marcgri to sync.

**Comment by marcgri** [comment]
Hi Antoine,

If you can help me sync with this deleted file update, that would be great. I know how to sync my repo with master, but not just a single file. The online answers are a bit confusing too.

I am also ready to push some of my Bl python code to our new repo, but I will need help with that too so I do it right.

Marc

**Comment by AntoineDujardin** [comment]
Removed from Marc's fork and mine.

**Comment by AntoineDujardin** [comment]
Removed from Bharat's fork & Iris did a fresh re-fork. Closing the issue.
