### ISSUE TITLE
Feature request: Display resolution rings on diffraction images

### ISSUE THREAD

**Issue by chuckie82** [chuckie82/pysingfel#20]

**Comment by AntoineDujardin** [comment]
One method would be to let the PnCCDDetector create a `matplotlib.patches.Circle`, to be added by the user by `ax.add_patch(...)`.
To create the Circle, we need to know:
- the position of the beam center in the pixel coordinates of the assembled detector
- the radius.

For the radius, we have the same formula as for the pixel position reciprocal. That shouldn't be an issue.

For the center, if we assume that the beam and the detector are aligned, we just need the pixel coordinates of the detector center.
The pixel coordinates are given by `GeometryAccess(...).get_pixel_coord_indexes()`.
I still need to dig into it.

**Comment by AntoineDujardin** [comment]
I can actually get the pixel coordinates from `GeometryAccess(...).point_coord_indexes()`.
However, the radius is trickier than I thought. I'm still struggling to find the right real distance corresponding to the reciprocal one.
