### ISSUE TITLE
Short path for geometry file likely to break

### ISSUE THREAD

**Issue by AntoineDujardin** [chuckie82/pysingfel#36]
I noted the recent following change commits 4da07da and b29311b, coming from the geometry file added in commit 95724f3:
```
     det = ps.PnccdDetector(
-        geom=ex_dir_+'/lcls/amo86615/'
-             'PNCCD::CalibV1/Camp.0:pnCCD.1/geometry/0-end.data',
+        geom=ex_dir_+'/input/geometry/0-end.data',
         beam=beam)
```
In Python 2 / psana 1, the `PNCCD::CalibV1` part might be needed to get the pedestals.
The doc says, in an error message:
> Sorry, at present, the package is not very smart. Please specify the path of the detector as deep as the geometry profile.
> And example would be like: /reg/d/psdm/amo/experiment_name/calib/group/source/geometry/0-end.data where the '/calib/group/source/geometry/0-end.data' part is essential. The address before that part is not essential and can be replaced with your absolute address or relative address.

In Python 3 / psana 2, the `amo86615` part is needed to get the pedestals (through the call to MongoDB).

**Comment by AntoineDujardin** [comment]
See #11

**Comment by chuckie82** [comment]
psana1 is fine with my current change. It's passing the tests.
I didn't realise python3 psana2 requires the amo86615 part. I'm still looking into getting pytest to pass.

**Comment by AntoineDujardin** [comment]
The change is perfectly fine in Py2/psana1 if we just want to get the geometry, but is not going to be extendable to the calibration parameters.

The rest of the tree is needed to get the pedestals and the pixels rms/mask/bkgd/status/gain.
To get these, pysingfel takes the full path to the geometry file, goes back to the parent folder, and extracts some information (detector type) from earlier points in the path.

With the short version, all calibration parameters are set to zero by default.

**Comment by chuckie82** [comment]
I will add a test for checking nonzero pedestals
