### ISSUE TITLE
Verify atoms types

### ISSUE THREAD

**Issue by AntoineDujardin** [chuckie82/pysingfel#47]
In the form factor tables, the variant O2p is key both to O and OH.
Since it's currently a suite of conditional statements, only the first one is used, but that might hide a bug.

Do we have a source for these coefficients?

**Comment by chuckie82** [comment]
Looks like it's from here:
https://svn.salilab.org/imp/trunk/modules/saxs/src/FormFactorTable.cpp

There are some lines that are commented out. O2p is one of the lines that shouldn't be there.

**Comment by AntoineDujardin** [comment]
I noted anomalies with CG1, C1p, C2p, C3p, C4p, and O2p.
The one with CG1 is the same as in the link.
The CXp ones were due to a indent error in Mark's code.
For the O2p one, Mark had un-commented the commented one.
Reviewing the link in more details, I also noted that O1A, O2A, OT1, OT2 were commented out, so I did the same.
