### ISSUE TITLE
Get rid of ROOT_DIR and sys.path in code

### ISSUE THREAD

**Issue by chuckie82** [chuckie82/pysingfel#63]
@AntoineDujardin 
Install pysingfel with
pip install -e .
and define pysingfel.dir to eliminate need to define ROOT_DIR and sys.path in the code

This instruction would need to go on top of the README

**Comment by fredericpoitevin** [comment]
Following Antoine's guidance, this seems to be working for me:


# psbuild-rhel7
## install LCLS2
Do this once in a while
```
ssh from pslogin
cd $HOME
cd lcls2
git clone https://github.com/fredericpoitevin/lcls2.git
source setup_env.sh
./build_all.sh
```
In `~/.bashrc`, we added:
```
if [[ $HOSTNAME == *"psbuild"* ]]; then 
  export PATH=${HOME}/lcls2:$PATH
  source setup_env.sh 
fi
```
## python kernel and jupyter
Once the environment is activated (`source setup_env.sh` from `lcls2` above), we create a local kernel environment that can be loaded from jupyterlab
```
(env_name)$ pip install ipykernel
(env_name)$ pip install ... (libraries of choice)
(env_name)$ python -m ipykernel install --user --name myenv --display-name MyEnv
```
Then on `https://pswww.slac.stanford.edu/` select your kernel of choice!

## adding psana and pysingfel to the kernel libraries
`build_all.sh` do not install locally by default, so we need to do it manually for psana:
```
cd ${HOME}/lcls2/psana
python setup.py install --instdir=${HOME}/.local --prefix=${HOME}/.local
```
Also for pysingfel (assuming you git cloned it first):
```
cd ${HOME}/Toolkit/pysingfel
(ps-3.1.11) [fpoitevi@psbuild-rhel7-01 pysingfel]$ pip install -e .
```
