### ISSUE TITLE
Photon integration in the previous pysingfel radiationDamage.py script

### ISSUE THREAD

**Issue by JunCEEE** [chuckie82/pysingfel#96]
Hi @chuckie82, this radiationDamage.py script created a long time ago was implemented in SimEx to generate diffraction patterns from the PMI output of XMDYN. When I checked the codes, I found an inconsistency between what we expected and what we got from the code. The formulas were derived from the [supplementary material](https://static-content.springer.com/esm/art%3A10.1038%2Fsrep24791/MediaObjects/41598_2016_BFsrep24791_MOESM51_ESM.pdf) of Chuck's [2016srep paper](https://www.nature.com/articles/srep24791).
![image](https://user-images.githubusercontent.com/3163505/98690215-ff347480-236c-11eb-8a9c-32720d39ba3a.png)

![image](https://user-images.githubusercontent.com/3163505/98552778-2a509280-229f-11eb-8c00-5da5fd12aa2e.png)

The code excerpt from pysingfel/radiationDamage.py:
https://github.com/chuckie82/pysingfel/blob/bef7ac9d47020e8f019f3cc79b6a0ec53790c2d9/pysingfel/radiationDamage.py#L146-L179
If my understanding is correct, these lines https://github.com/chuckie82/pysingfel/blob/bef7ac9d47020e8f019f3cc79b6a0ec53790c2d9/pysingfel/radiationDamage.py#L171-L174 should be modified to
```
        detector_intensity += photon_field*beam.get_photons_per_pulse_per_area()
   detector_intensity *= (det.solid_angle_per_pixel *
                           det.polarization_correction)
```
to manifest the expected function in the picture.  

Do you have any comments on that? Is there a new script to conduct similar computing in this new version of pySingFEL?

By the way, The `total_phot` was calculated on line 160 but was not called in the code.

**Comment by chuckie82** [comment]
@irischang0202 please verify what is the correct implementation for detector_intensity.

**Comment by irischang020** [comment]
> @irischang020 please verify what is the correct implementation for detector_intensity.
From the [supplementary material](https://static-content.springer.com/esm/art%3A10.1038%2Fsrep24791/MediaObjects/41598_2016_BFsrep24791_MOESM51_ESM.pdf) page 9 of the paper:
`In our case study, a single diffraction pattern of an exploding protein, as seen by the detector, is calculated as the incoherent sum of diffraction patterns at each instance in time during the entire duration of the XFEL pulse. In order to keep the calculation tractable, we (1) use the mean photon energy of the X-ray pulse instead of the entire SASE spectrum, (2) downsample the effective detector pixel size, (3) generate multiple diffraction patterns per PMI trajectory, and (4) decrease the number of temporal samples of the radiation damage process.
The mean photon energy is defined in eq. 4, and this simplification is expected to have little effect on the validity of the simulations for photon energies away from absorption edges of atoms in the sample. Near edges, the full spectrum could be used at the expense of computational time.`
The current implementation in the radiationDamage.py is a simplification to make the calculation faster.

**Comment by chuckie82** [comment]
thanks @JunCEEE 
I think you are right.
When set_fluence_from_file(input_name, time_slice, slice_interval, beam) is used to update beam fluence, this should be multiplied inside the while loop (not outside)

**Comment by chuckie82** [comment]
@irischang020 could you make these changes:
https://github.com/JunCEEE/pysingfel/commit/0fb05133370ba954646ee2655bb59bf2f2ad19d9
then close this comment

**Comment by JunCEEE** [comment]
@chuckie82 Thanks for the confirmation. This clarification is important for simulation data interpolation. 

I tried this script with the current master branch of pysingfel, but got some errors like this:
```
Traceback (most recent call last):
  File "/gpfs/exfel/data/user/juncheng/miniconda3/envs/pysingfel2/bin/radiationDamageMPI", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/gpfs/exfel/data/user/juncheng/pysingfel2/bin/radiationDamageMPI", line 3, in <module>
    from pysingfel.radiationDamageMPI import main
  File "/gpfs/exfel/data/user/juncheng/pysingfel2/pysingfel/radiationDamageMPI.py", line 5, in <module>
    from pysingfel.radiationDamage import *
  File "/gpfs/exfel/data/user/juncheng/pysingfel2/pysingfel/radiationDamage.py", line 2, in <module>
    from pysingfel.particle import rotate_particle, Particle
ImportError: cannot import name 'rotate_particle' from 'pysingfel.particle' (/gpfs/exfel/data/user/juncheng/pysingfel2/pysingfel/particle.py)
```
It seems due to the change of function name or usage. Do you think we need to update this script or do you have another script with similar functionality and new-pysingfel-compatibility?

**Comment by fredericpoitevin** [comment]
Hi @JunCEEE , this should work now, it has been fixed in #100

**Comment by JunCEEE** [comment]
Hi @fredericpoitevin, thanks. Unfortunately, it didn't solve my problem. When I try this 
```
radiationDamageMPI --inputDir w4_noW/pmi_out --outputDir $OUT_DIR  --geomFile tmp.geom --configFile /dev/null   --calculateCompton 1 --sliceInterval 50 --numSlices 100 --pmiStartID 1 --pmiEndID 100 --numDP 1
```
I still get the error like [this](https://github.com/chuckie82/pysingfel/issues/96#issuecomment-726078481).

I am not sure if this way to run pysingfel is still maintained. I know this way from my predecessor in EuXFEL. The bin file still exists in the current [repository](https://github.com/chuckie82/pysingfel/tree/master/bin) If there is a better way to run pysingfel reading pmi_out h5 files and geomfile, please give me a hint.

**Comment by chuckie82** [comment]
radiationDamageMPI isn't maintained in the new version of pysingfel, but we should work together to make it work again. I think we will need access to pmi_out data.

**Comment by JunCEEE** [comment]
Hi @chuckie82, please find the pmi_out test data here: https://syncandshare.desy.de/index.php/s/TeCa5GWNfpw8eNm
It would be nice to work together and fix it. Since it seems like a lib compatibility problem at the first glance, I could try to fix it from my side and submit a pull request until I cannot move forward. What do you think?

**Comment by chuckie82** [comment]
@JunCEEE thanks for the pmi_out test data.
A PR would be much appreciated and our team can look into issues as they arise.

**Comment by JunCEEE** [comment]
@chuckie82 Okay, I'll have a try and give some updates next week.

**Comment by chuckie82** [comment]
@JunCEEE we've renamed pysingfel to skopi and moved to:
https://github.com/chuckie82/skopi
Future PRs/issues should go there. thanks

**Comment by JunCEEE** [comment]
Thanks for informing me! I have some ideas about the AGIPD detector. I’ll discuss it in a new issue.
